development:
  adapter: postgresql
  encoding: unicode
  database: toucan_notes_development
  pool: 5
  username: toucan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: toucan_notes_test
  pool: 5
  username: toucan
  password:
